### ISSUE TITLE
Instructions unclear; cannot run locally

### ISSUE THREAD

**Issue by gberardi-pillar** [ranman/spaces-v-tabs#1]
I tried to follow along with https://aws.amazon.com/blogs/aws/new-aws-sam-local-beta-build-and-test-serverless-applications-locally/ and hit a deadend in which the local DynamoDB table I setup seemed inaccessible to the local lambda I had running. 

I pulled the git repo of this project, modified it to point to my local DynamoDB IP/port, and when I run `sam local start-api` and try to do an Http Request (POST) to it, I get:

```
2019/11/12 11:15:58 Function lambda_function.lambda_handler timed out after 20 seconds`
2019/11/12 11:15:58 Error invoking python3.6 runtime: io: read/write on closed pipe
```

When I do:
`$ awslocal dynamodb list-tables --endpoint-url http://localhost:8000`
I see 
```{
    "TableNames": [
        "spaces-tabs-votes"
    ]
}
```

My change to the lambda handler code was to get rid of the environment variable check and simply do:

```
votes_table = boto3.resource('dynamodb', endpoint_url="http://localhost:8000/").Table("spaces-tabs-votes")
```

If I change the timeout to 300 from 20, I instead see this error: 
```
Could not connect to the endpoint URL: "http://localhost:8000/": EndpointConnectionError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 26, in lambda_handler
    ReturnValues='ALL_NEW'
  File "/var/runtime/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/var/runtime/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/var/runtime/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/var/runtime/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/var/runtime/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/var/runtime/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/var/runtime/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/var/runtime/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/var/runtime/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/var/runtime/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/var/runtime/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/var/runtime/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/var/runtime/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/var/runtime/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/var/runtime/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/var/runtime/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/var/runtime/botocore/endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "/var/runtime/botocore/httpsession.py", line 282, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://localhost:8000/"

END RequestId: 36a86cf1-3c4a-4608-a7f2-dcd3d1d79c26
```

My best guess is that the local lambda and the local dynamo instances can't seem to talk to each other, but I do not know what I need to do to change this fact or if my guess is correct.

**Comment by gberardi-pillar** [comment]
On a separate but related note, the instructions also say `So we create a DynamoDB table that we expose to our Lambda function through an environment variable called ` but says nothing about how to do so, so I had to piece together clues from what the lambda code was doing to the database to create it, and I wish the original article simply said "Make a table named XYZ, and make sure it has these specific keys with these specific types".

**Comment by gberardi-pillar** [comment]
Ok, so part of the issue was that I was using localhost:8000 instead of the original docker.for.mac.localhost. So I had to setup my local DynamoDB container AND start the lambda container on the same docker network. I could use docker-compose, but since I didn't, I did:

```
$ docker network create lambda-local
$ sam local start-api --docker-network lambda-local
$ docker run -p 8000:8000 --network lambda-local --name dynamodb amazon/dynamodb-local
```

So now I have both the local lambda and the dynamodb containers on the same docker network, which means that they can see each other. I changed the code to:

```
votes_table = boto3.resource('dynamodb', endpoint_url="http://dynamodb:8000/").Table("spaces-tabs-votes")
```

But then it couldn't see the table I created using:

```
awslocal dynamodb create-table --table-name spaces-tabs-votes --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --key-schema AttributeName=id,KeyType=HASH --attribute-definitions AttributeName=id,AttributeType=S --endpoint-url http://localhost:8000
```

A colleague said this sounded familiar, and he suggested looking into credentials in that I might have somehow used different credentials between my create-table, and then we changed the creation of the dynamo to:

```
$ docker run -p 8000:8000 --network lambda-local --name dynamodb amazon/dynamodb-local -jar DynamoDBLocal.jar -sharedDb -inMemory
```

And after creating the table and then running the lambda, it connects. Apparently because it's now a  shared DB it wasn't using random credentials? Not sure. 

But hopefully this helps someone.
